name: "Release"

on:
  release:
    types: [published]

jobs:
  deploy:
    name: "Deploy to Netlify"
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_SITE_ID: ${{INIT_COUNTER_SITE_ID}}
